"""Initial migration with all models

Revision ID: 5d8efe30a44b
Revises: 
Create Date: 2026-02-23 18:58:10.214189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8efe30a44b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professions')),
    sa.UniqueConstraint('name', name=op.f('uq_professions_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('business_category', sa.String(length=150), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('business_logo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_profiles_user_id'))
    )
    op.create_table('code_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('quiz_url', sa.String(length=500), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], name=op.f('fk_code_quizzes_profession_id_professions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_quizzes'))
    )
    op.create_table('developer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=150), nullable=False),
    sa.Column('profile_picture', sa.String(length=200), nullable=False),
    sa.Column('github_account', sa.String(length=100), nullable=True),
    sa.Column('linkedin_account', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('available_time', sa.String(length=50), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('proficiency_points', sa.Integer(), nullable=True),
    sa.Column('courtesy_points', sa.Integer(), nullable=True),
    sa.Column('last_proficiency_award_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_developer_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_developer_profiles_user_id'))
    )
    op.create_table('exam_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], name=op.f('fk_exam_links_profession_id_professions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_links'))
    )
    op.create_table('hackathons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_link', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('prize_pool', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], name=op.f('fk_hackathons_profession_id_professions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hackathons'))
    )
    op.create_table('client_developers',
    sa.Column('client_profile_id', sa.Integer(), nullable=False),
    sa.Column('developer_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('fk_client_developers_client_profile_id_client_profiles')),
    sa.ForeignKeyConstraint(['developer_profile_id'], ['developer_profiles.id'], name=op.f('fk_client_developers_developer_profile_id_developer_profiles')),
    sa.PrimaryKeyConstraint('client_profile_id', 'developer_profile_id', name=op.f('pk_client_developers'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('location_details', sa.Text(), nullable=True),
    sa.Column('roles_and_responsibilities', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('desired_skills', sa.JSON(), nullable=True),
    sa.Column('experience_required', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], name=op.f('fk_jobs_client_id_client_profiles')),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_profiles.id'], name=op.f('fk_jobs_developer_id_developer_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_comments_job_id_jobs')),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('jobs')
    op.drop_table('client_developers')
    op.drop_table('hackathons')
    op.drop_table('exam_links')
    op.drop_table('developer_profiles')
    op.drop_table('code_quizzes')
    op.drop_table('client_profiles')
    op.drop_table('users')
    op.drop_table('professions')
    # ### end Alembic commands ###
