"""added cascade field in relationships

Revision ID: 6deb4046fa7e
Revises: 537a9b1f35ab
Create Date: 2025-01-21 14:17:27.830195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6deb4046fa7e'
down_revision = '537a9b1f35ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_profiles_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_client_profiles_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_client_id_client_profiles', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jobs_client_id_client_profiles'), 'client_profiles', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_client_id_client_profiles'), type_='foreignkey')
        batch_op.create_foreign_key('fk_jobs_client_id_client_profiles', 'client_profiles', ['client_id'], ['id'])

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_client_profiles_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_client_profiles_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
