"""initial migration

Revision ID: 714817f0c052
Revises: 
Create Date: 2025-01-20 17:22:10.040034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714817f0c052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_client_profiles_user_id'))
    )
    op.create_table('developer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.String(length=200), nullable=True),
    sa.Column('available_time', sa.String(length=50), nullable=True),
    sa.Column('github_account', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_developer_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developer_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_developer_profiles_user_id'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('admin_viewed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], name=op.f('fk_comments_client_id_client_profiles')),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_profiles.id'], name=op.f('fk_comments_developer_id_developer_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profiles.id'], name=op.f('fk_jobs_client_id_client_profiles')),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_profiles.id'], name=op.f('fk_jobs_developer_id_developer_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('comments')
    op.drop_table('developer_profiles')
    op.drop_table('client_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
