"""Add multi-role auth

Revision ID: a5e8b85b7c93
Revises: c92af09081ef
Create Date: 2026-02-15 13:51:30.488421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e8b85b7c93'
down_revision = 'c92af09081ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_logo', sa.String(length=200), nullable=False))
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('business_description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_account', sa.String(length=100), nullable=True))
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_profiles', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('linkedin_account')

    with op.batch_alter_table('client_profiles', schema=None) as batch_op:
        batch_op.alter_column('business_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('business_logo')

    # ### end Alembic commands ###
