"""Add experience and points fields to developer profiles

Revision ID: add_exp_points_001
Revises: fab1fdace998
Create Date: 2026-02-16 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_exp_points_001'
down_revision = 'fab1fdace998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developer_profiles', sa.Column('years_of_experience', sa.Integer(), nullable=True))
    op.add_column('developer_profiles', sa.Column('proficiency_points', sa.Integer(), server_default='0', nullable=True))
    op.add_column('developer_profiles', sa.Column('courtesy_points', sa.Integer(), server_default='0', nullable=True))
    op.add_column('developer_profiles', sa.Column('last_proficiency_award_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developer_profiles', 'last_proficiency_award_date')
    op.drop_column('developer_profiles', 'courtesy_points')
    op.drop_column('developer_profiles', 'proficiency_points')
    op.drop_column('developer_profiles', 'years_of_experience')
    # ### end Alembic commands ###
