"""add_job_details

Revision ID: add_job_details_001
Revises: fab1fdace998_remake
Create Date: 2026-02-23 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_job_details_001'
down_revision = 'fab1fdace998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.String(50), nullable=True))
        batch_op.add_column(sa.Column('hours_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_type', sa.String(20), nullable=True))
        batch_op.add_column(sa.Column('location_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('roles_and_responsibilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('desired_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('experience_required', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('experience_required')
        batch_op.drop_column('desired_skills')
        batch_op.drop_column('requirements')
        batch_op.drop_column('roles_and_responsibilities')
        batch_op.drop_column('location_details')
        batch_op.drop_column('location_type')
        batch_op.drop_column('hours_per_week')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
