"""remake

Revision ID: fab1fdace998
Revises: a5e8b85b7c93
Create Date: 2026-02-15 19:03:14.069261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab1fdace998'
down_revision = 'a5e8b85b7c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_developers',
    sa.Column('client_profile_id', sa.Integer(), nullable=False),
    sa.Column('developer_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], name=op.f('fk_client_developers_client_profile_id_client_profiles')),
    sa.ForeignKeyConstraint(['developer_profile_id'], ['developer_profiles.id'], name=op.f('fk_client_developers_developer_profile_id_developer_profiles')),
    sa.PrimaryKeyConstraint('client_profile_id', 'developer_profile_id', name=op.f('pk_client_developers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_developers')
    # ### end Alembic commands ###
